### ISSUE TITLE
데브 이벤트 상단 공지 배너(?) 변환

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#10]
@Limm-jk 님 안녕하세요~

다름이 아니라 데브 이벤트 상단 베너를 정리하였습니다.

![스크린샷 2021-11-10 오후 11 07 12](https://user-images.githubusercontent.com/28642484/141127915-832a2f05-2707-46b7-af23-5f2d90a3cf55.png)

혹시 크롤링 코드에 영향이 없을지 확인차 이슈 남깁니다!

감사합니다^^

**Comment by Limm-jk** [comment]
아하 확인했습니다 :) 감사합니다!!

**Comment by KoEonYack** [comment]
확인 감사합니다 ~ 👍
