### ISSUE TITLE
Dev-Event 구독 서비스 유저가 1k가 되었습니다!

### ISSUE THREAD

**Issue by Limm-jk** [brave-people/Dev-Event-Subscribe-Script#11]
![image](https://user-images.githubusercontent.com/57378834/147024909-8b286e46-859b-4694-ae6b-ba1aff96f91d.png)

멋지네요 :)

**Comment by KoEonYack** [comment]
최고네요~!!

@Limm-jk 님 서비스를 운영해주셔서 감사합니다 👍 👍 👍 

살짝 앞으로의 계획을 말씀드리면

데브 이벤트가 내년 초 웹으로 오픈 예정입니다.! (본업이 있는지라 언제까지나 예상이며 일정은.. 밀릴수있지만요..ㅠㅠ)

데브 이벤트 이메일 구독도 크롤링 방식에서 API 방식으로, 행사 썸네일 이미지도 같이 보낼 수 있을 것입니다!

내년에도 여력이 되신다면? 데브 이벤트 이메일 구독 API 전환에 함께해주시면 큰 영광입니다^^

감사합니다!

(dev event web team cc. @osj3474 , @leedoopal )

**Comment by Limm-jk** [comment]
@KoEonYack 좋습니다 :)

저는 데브 이벤트 잘 운영한 덕분인지 올해가 가기 전에 본업이 생겼네요 ㅎㅎㅎㅎㅎ

내년에도 많은 이들이 쓰는 서비스가 되었으면 좋겠습니다~

**Comment by osj3474** [comment]
너무 멋져요~~~ ⭐️

용감한 친구들 forever

**Comment by KoEonYack** [comment]
@Limm-jk  취뽀를 축하드립니다~!!^^ 

[Blog. 오픈소스 용감한 친구들 21년 회고](https://covenant.tistory.com/265) 글을 작성하였습니다. 시간나실때 읽어보세요~


새해 복 많이 받으시고!

@channel-io 에서 승승장구하시길 응원합니다!👏👏👏
