### ISSUE TITLE
1월 4째주 개발자 행사 Link Issue

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#12]
@Limm-jk 님 잘 지내시나요~!

제 지인인 분이 힙주비에서 준규님을 뵈었다고 하는데요~ 이 바닥 좁다는 생각이 듭니다^^..

다름이 아니라 이번주 [Email](https://github.com/brave-people/Dev-Event-Subscribe/issues/60) 에 댓글대로 

1월 우아한 테크 세미나 링크가 잘 걸려있지않네요! Dev-Event는 링크가 잘 걸려있어서 확인 부탁드립니다!

Dev-Event-Subscribe 저장소의 issue에 다른 분이 댓글을 달면 watch를 누른 모든분에게 댓글 내용이 전송되어서 불편을 가져올것 같습니다. 

제가 예전에 Dev-Event-Subscribe 저장소에 용감한 친구들 맴버가 아니면 이슈 혹은 댓글을 못달게 막았는데... 지금 다시 찾아보니 해당 기능이 없어진것 같네요(쫌 찾아보니 엔터프라이즈 버전으로 빠진것 같기도하고요..)

혹시 관련해서 기능을 발견하거나 다른 아이디어가 있다면 알려주세요!

늘 감사합니다 :)

**Comment by Limm-jk** [comment]
한번 확인해보겠습니다 :) 감사합니다!!

**Comment by Limm-jk** [comment]
정작 업데이트 하는 저는 메일을 받아볼 수가 없어서 디버깅이 늦어지는군요..! ㅋㅋㅋㅋㅋㅋ

**Comment by KoEonYack** [comment]
깃헙 부계정 파셔서 watch 누르시는것을 추천드립니다 ~ !! ㅋㅋ

**Comment by Limm-jk** [comment]
![image](https://user-images.githubusercontent.com/57378834/150896574-0bfe1d24-8689-4c30-9c48-88a5428da59b.png)

여기서 설정 가능한 것 같습니다! 요거 확인해주시고, 원하는 방향성이 맞다면 활성화 해주시면 될 것 같아요!

**Comment by KoEonYack** [comment]
오 있었네요 ㅜㅜ 감사합니다! 일단 한달동안 코멘트 달지 못하도록 설정해두었습니다 👍

**Comment by Limm-jk** [comment]
위 이슈로 해결했습니다!
이전에 간헐적으로 등록되던 링크가 따로 올라오는 포멧을 지원하기 위하여 만든 분기문이었는데 해당 로직이 예측하지 못하게 동작하고 있었네요

**Comment by KoEonYack** [comment]
그렇군요! 빠른 수정 감사합니다! 👍 👍 👍

**Comment by Limm-jk** [comment]
감사합니다 :)
그나저나 힙주비에 아는 분이 있으시다니.. 업계 진짜 좁네요 ㅋㅋㅋ

**Comment by Limm-jk** [comment]
그리고 글 막는거 우선 6개월씩 막아두고 필요할 때 바꿔도 될 것 같아요 :)

**Comment by KoEonYack** [comment]
그러게 말입니다~^^ 

넵! 감사합니다. 6개월로 늘리는것도 좋겠네요!

발신받은 구독 이메일에 이슈있을시 제보할곳도 만드러야겠네요!

해당 이슈는 종료하겠습니다!

평안한 밤 되세요 🌙
