### ISSUE TITLE
4월 첫째주 구독 이메일 미발송

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#14]
@Limm-jk 님 안녕하세요~

오늘자 이메일 발송이 안되었는데요~ 확인 부탁드립니다~~!

**Comment by Limm-jk** [comment]
저장소에 60일간 커밋이 없으면 깃헙 액션이 꺼지는군요..! 
[ref](https://github.community/t/no-notification-workflow-disabled-after-60-days/182169)

대책은 [해당 스크립트](https://github.com/gautamkrishnar/keepalive-workflow)를 활용하여 안멈추게 하는 방향으로 해보겠습니다.
해당 스크립트 55일 정도 이후에 잘 작동되었는지 확인해볼게요.

**Comment by Limm-jk** [comment]
이번주는,,, 지금이라도 보내는게 좋을까요? 아니면 아예 스킵하는 방향이 좋을까요?

**Comment by KoEonYack** [comment]
@Limm-jk 그런 문제가 있었군요! 알려주셔서 감사합니다!

이번주는 스킵하죠~!

확인 감사합니다!! 👍
