### ISSUE TITLE
구독 설명 문구를 작성했어요!

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#7]
@Limm-jk 

[Dev-Event-Subscribe](https://github.com/brave-people/Dev-Event-Subscribe)에 이메일 구독 설명 문구를 작성했어요!

확인해보시고 추가할 부분 있으면 알려주세요 :)

오늘 저녁 8시 전에 카카오톡 오픈 채팅방 총 5곳 3600명을 대상으로 홍보가 될꺼에요~ 

초기에 어느 정도 신청할지 저도 잘 모르겠지만 너무 적더라도 실망하지마세요!! 

적은 사용자라도 최고의 서비스를 제공해주는 것이  중요하니깐요 :)

**Comment by Limm-jk** [comment]
시간보다 10분정도 늦어지는 것 같지만, 잘 발급되고 있는 것 같네요!!

이전 데모 저장소 유지하면서 잘 돌아가는 지 모니터링 하겠습니다 :)

**Comment by KoEonYack** [comment]
최고네요!! 👍👍 

현재 18명의 구독자가 있네요!!!  

딱 10분은 아니여도 괜찮아요! 감사합니다 :)

**Comment by Limm-jk** [comment]
기간을 한달로 제한을 걸어봤습니다. 지금이 2월 17일이라면 3월 17일까지 해당되는 행사만 잡히게 만들어보았어요!

우선 돌아가게만 대충 짜서 코드는 주말에 다시 한번 보겠습니다 ㅎ,,ㅎㅎ,,,

혹시 원하시는 기능이 있으시다면 편하게 말씀해주세요!! 가능한 한에서..! 잘 만들어보겠습니다 :)

**Comment by KoEonYack** [comment]
@Limm-jk 

3월은 Link위치가 변경되었는데 빠르네요!! 👍👍

서비스 공개 5일차 메일 구독자가 30명인데 새로운 가치를 만들어냈다는 뿌듯함이 있으실까요?!😆

3일뒤면 처음으로 구독자들에게 메일이 가겠네요!!! 

새로운 기능이 있으면 Issue 알릴께요~!! 감사합니다 :)

**Comment by Limm-jk** [comment]
아웃풋이 나오는 개발을 하는 것, 그리고 누군가에게 도움이 되는 개발은 정말 재미있는 것 같습니다😀

하지만, 선보일 때 긴장됨은 어쩔 수가 없네요 ㅋㅋㅋㅋㅋ

가치를 찾는 일은 항상 즐거운 일입니다 :)

**Comment by KoEonYack** [comment]
좋은 성장 포인트를 찾으셨네요!! 👍

훌륭한 개발자로 성장하시겠어요!! 

좋은 밤 되세요!! 🌙
