### ISSUE TITLE
Github Trending

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#8]
@Limm-jk 

안녕하세요~! 잘지내시는지요 :)

[Github Tranding](https://github.com/trending?since=monthly)
- Filter: Spoken Language: Korean, This month

---------

![스크린샷 2021-05-10 오후 8 50 39](https://user-images.githubusercontent.com/28642484/117654935-61ade680-b1d1-11eb-8e8b-014bf0d421b5.png)

--------

Dev Event Subscribe가 Github Tranding에 있네요!
구독 기능을 생각도 안했는데 좋은 제안에 이어 개발을 해주셔서 Tranding에 잡히지 않았나 생각이 듭니다.

감사한 마음에 글 적어봅니다!
평안한 밤 되세요!😀

**Comment by Limm-jk** [comment]
헉 세상에

**Comment by Limm-jk** [comment]
항상 풍성하게 저장소 운영해주셔서 감사합니다 :)

덕분에 별 것 아닌 코드가 빛을 보는 것 같습니다 ㅎㅎ

**Comment by KoEonYack** [comment]
@Limm-jk 

부족한 저장소 운영의 한 부분을 담당해 주셔서 늘 감사할 뿐입니다!
즐거운 저녁 잘 마무리하세요!! :)
