### ISSUE TITLE
Cover image, link 추가!

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Subscribe-Script#9]
@Limm-jk 안녕하세요~! 잘 지내시나요?!

개선 방향이 있어서 말씀드립니다!

-------

## 커버 이미지 추가!

현재 Dev Event 커버이미지가 예전 버전이며, 크기가 크기에(가로 1300px) 새로운 Cover image를 알려드립니다!

Cover image: https://github.com/brave-people/Dev-Event/blob/master/static/title-v3-md.png

## 문구 추가!

Cover image 바로 아래에 

더 많은 행사를 보고 싶다면? [Github Dev Event](https://github.com/brave-people/Dev-Event)로 오세요!

문구를 넣었으면 좋겠습니다!
-------

늘 감사합니다 👍 

평안한 저녁 되세요!!
Covenant

**Comment by Limm-jk** [comment]
@KoEonYack 
커버이미지가 예쁘게 바뀌었군요!! 좋습니다 :)
문구 추가하고 가운데 맞춤해보았습니다.
해당 사항 확인 후 피드백 사항 있다면 알려주세요.

[결과물](https://github.com/Limm-jk/Dev-Event-Mailing-Service/issues/127)

**Comment by KoEonYack** [comment]
@Limm-jk 

잘 반영되었네요!!

빠른 반영 감사합니다!!! 👍 💯 

작업 완료되었으니 이슈는 닫을께요~!!
